-- Deal-scraper cloud tables. Run once in the Supabase SQL editor.
-- The Edge Function (service role) writes alerts; the phone/desktop (authed user) read them.

create table if not exists public.deal_watches (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  query       text not null,
  max_price   numeric not null,
  sources     text,                         -- JSON array of source keys, or null = all
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.deal_alerts (
  id          bigint generated by default as identity primary key,
  watch_id    bigint not null references public.deal_watches (id) on delete cascade,
  user_id     uuid not null,
  source      text not null,
  listing_id  text not null,
  title       text,
  price       numeric,
  url         text,
  image_url   text,
  found_at    timestamptz not null default now(),
  dismissed   boolean not null default false,
  -- Per-watch dedup: two different watches that match the same listing each get their own
  -- alert row (a global (source, listing_id) key would drop the second watch's alert).
  unique (watch_id, source, listing_id)
);

create index if not exists deal_alerts_user_found on public.deal_alerts (user_id, found_at desc);

-- Row-level security: each user only sees their own rows.
alter table public.deal_watches enable row level security;
alter table public.deal_alerts  enable row level security;

drop policy if exists "watches are private" on public.deal_watches;
create policy "watches are private" on public.deal_watches
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "alerts are private" on public.deal_alerts;
create policy "alerts are private" on public.deal_alerts
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- (The Edge Function uses the service-role key, which bypasses RLS, to insert alerts.)
