-- Decks: a named list of cards (main/extra/side). Run once in the SQL editor.

create table if not exists public.decks (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name        text not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.deck_cards (
  id          bigint generated by default as identity primary key,
  deck_id     bigint not null references public.decks (id) on delete cascade,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  card_id     text not null,                       -- 8-digit passcode
  name        text,
  image_url   text,
  count       integer not null default 1,
  section     text not null default 'main',        -- main | extra | side
  created_at  timestamptz not null default now()
);

create index if not exists deck_cards_deck on public.deck_cards (deck_id);

alter table public.decks       enable row level security;
alter table public.deck_cards  enable row level security;

drop policy if exists "decks are private" on public.decks;
create policy "decks are private" on public.decks
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "deck_cards are private" on public.deck_cards;
create policy "deck_cards are private" on public.deck_cards
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());
