-- supabase/price_alerts_schema.sql — Spec G2 §4. Einmal im Dashboard einspielen (idempotent).
-- Setzt voraus: public.set_updated_at() (supabase/schema.sql) und public.price_reference (G1,
-- supabase/price_reference_rpc.sql). Ausgewertet wird nur von der Edge Function evaluate-price-alerts.

create table if not exists public.price_alert_rules (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  kind        text not null check (kind in ('move', 'above', 'below')),
  card_id     text,
  set_code    text,
  language    text,
  rarity      text,
  pct         numeric check (pct between 1 and 500),
  min_eur     numeric check (min_eur >= 0),
  days        integer check (days in (7, 30)),
  threshold   numeric check (threshold > 0),
  armed       boolean not null default true,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  -- move: global, ohne Printing, mit pct/min_eur/days. above/below: ein Printing mit threshold.
  constraint price_alert_rules_shape check (
    (kind = 'move'
      and card_id is null and set_code is null and language is null and rarity is null
      and pct is not null and min_eur is not null and days is not null and threshold is null)
    or
    (kind in ('above', 'below')
      and card_id is not null and set_code is not null and language is not null and rarity is not null
      and threshold is not null and pct is null and min_eur is null and days is null)
  ),
  -- Hoechstens ein above und ein below je Printing. Bei move sind die Schluesselspalten null und
  -- kollidieren deshalb nicht; dafuer sorgt der Teilindex unten.
  constraint price_alert_rules_target_unique unique (user_id, kind, card_id, set_code, language, rarity)
);

create unique index if not exists price_alert_rules_one_move
  on public.price_alert_rules (user_id) where kind = 'move';

drop trigger if exists price_alert_rules_updated_at on public.price_alert_rules;
create trigger price_alert_rules_updated_at
  before insert or update on public.price_alert_rules
  for each row execute function public.set_updated_at();

create table if not exists public.price_alert_events (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  rule_id     bigint not null references public.price_alert_rules (id) on delete cascade,
  kind        text not null check (kind in ('move', 'above', 'below')),
  card_id     text not null,
  set_code    text not null,
  language    text not null,
  rarity      text not null,
  old_price   numeric,
  new_price   numeric not null,
  pct         numeric,
  days        integer,
  threshold   numeric,
  day         date not null,
  created_at  timestamptz not null default now(),
  dismissed   boolean not null default false,
  constraint price_alert_events_dedup unique (rule_id, card_id, set_code, language, rarity, day)
);

create index if not exists price_alert_events_open
  on public.price_alert_events (user_id, dismissed, id desc);

alter table public.price_alert_rules  enable row level security;
alter table public.price_alert_events enable row level security;

drop policy if exists "price alert rules are private" on public.price_alert_rules;
create policy "price alert rules are private" on public.price_alert_rules
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "price alert events are private" on public.price_alert_events;
create policy "price alert events are private" on public.price_alert_events
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- (Die Edge Function nutzt den Service-Role-Schluessel, der RLS umgeht.)
-- G1 hat price_reference nur fuer authenticated freigegeben; der Auswerter laeuft als service_role.
grant execute on function public.price_reference(integer) to service_role;
