-- Wishlist: cards the user wants. Each wishlist entry also spawns a deal_watch (by name),
-- so wanted cards are automatically hunted across the marketplaces. Run once in the SQL editor.

create table if not exists public.wishlist (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  card_id     text not null,                      -- 8-digit passcode (or free-text key)
  name        text not null,
  image_url   text,
  max_price   numeric,
  watch_id    bigint references public.deal_watches (id) on delete set null,
  created_at  timestamptz not null default now(),
  unique (user_id, card_id)
);

alter table public.wishlist enable row level security;

drop policy if exists "wishlist is private" on public.wishlist;
create policy "wishlist is private" on public.wishlist
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());
